"""ACCEPTANCE: the real weekly TQQQ reference algorithm, run unmodified on
dqengine.runtime, still lands where LEAN landed.

The reference is `golden/acceptance_tqqq_weekly.json`: the frozen fill-by-fill
result of dqengine.runtime's OWN run of the algorithm. First captured 2026-09-14,
when it was cross-checked one last time against the IR engine before that
engine's deletion -- the two agreed bit-exact on all 519 fills (day, time,
qty, price) and on the full equity curve. RE-PINNED 2026-09-19 after the bar
set's missing 12-31 regular sessions were backfilled: 520 fills, $13,603.38,
and a fresh LEAN run on the repaired bars matched all 520 one for one (day,
time, qty, price) and the end equity to the cent; everything before
2024-12-31 -- 404 fills, 1,004 equity days -- was identical to the old pin -- but the fixture's provenance is
dqengine.runtime, the engine that survives, not the oracle being retired. It is
COMMITTED, unlike the `parity_out.json` this test used to read -- that file
was gitignored and regenerated by run_parity.py, which ran the engine this
phase deletes, so a fresh clone had no reference at all and this gate
errored rather than skipping.

Two assertions, deliberately: against the frozen engine result (fill by
fill, which is what catches a one-share sizing change) and against LEAN's
own published numbers (which is what the frozen result is FOR). If the
fixture ever has to be regenerated, it can only be regenerated from
dqengine.runtime -- so the LEAN block is the part that cannot drift with us.

The frozen half is held to the same bar as the 66 golden cases
(parity._digest): every fill compared on (day, ms, qty) and the whole daily
equity curve compared day by day and cent for cent. It was not always --
this gate compared (day, qty) and two end stats while the fixture carried a
per-fill `ms` and 1,364 equity points that nothing read, so a change that
moved a fill within its session, or that re-marked the middle of the curve
without changing a single fill, passed. This is the only gate that pins the
LIVE strategy over its full 5.4-year window; it should be the strictest,
not the loosest.
"""
import json
import os

import pytest

from dqengine.config import data_root
from dqengine.runtime import run_python_backtest

HERE = os.path.dirname(__file__)
ENGINE = os.path.abspath(os.path.join(HERE, "..", ".."))
# the algorithm ships with the distribution, byte-identical to the file the
# LEAN reference run used (test_examples.py pins that in the monorepo)
ALGO = os.path.join(ENGINE, "dqengine", "examples", "tqqq_weekly.py")
DATA = data_root()      # DQENGINE_DATA_ROOT, or the checkout's data tree
REF = os.path.join(HERE, "golden", "acceptance_tqqq_weekly.json")

from conftest_helpers import reference_bars                           # noqa: E402
needs_data = reference_bars(DATA, "tqqq")


def _first_diff(got, want, label):
    """Name the first differing element. 520 fills and 1,364 equity points
    print as a wall of text otherwise, and the useful fact is always WHERE
    the two series part company."""
    for i, (a, b) in enumerate(zip(got, want)):
        if a != b:
            return (f"{label} diverge at index {i}: got {a!r}, "
                    f"frozen reference has {b!r} "
                    f"({sum(1 for x, y in zip(got, want) if x != y)} of "
                    f"{len(want)} differ)")
    return f"{label}: lengths differ, got {len(got)} want {len(want)}"


def _run():
    code = open(ALGO).read()
    res = run_python_backtest(code, data_root=DATA,
                              overrides={"start": "2021-01-04",
                                         "end": "2026-06-09",
                                         "cash": 1000.0})
    assert "error" not in res, res.get("error")
    return res


@needs_data
def test_tqqq_weekly_runs_unmodified_and_matches_the_frozen_reference():
    res, ref = _run(), json.load(open(REF))

    assert abs(res["stats"]["end_equity"] - ref["stats"]["end_equity"]) <= 1.0, \
        (res["stats"], ref["stats"])
    assert abs(res["stats"]["cagr_pct"] - ref["stats"]["cagr_pct"]) <= 0.1

    got = [(f["day"], f["qty"]) for f in res["fills"]]
    want = [(f["day"], f["qty"]) for f in ref["fills"]]
    assert len(got) == len(want), (len(got), len(want), got[:5], want[:5])
    assert got == want

    diffs = [abs(a["px"] - b["px"]) for a, b in zip(res["fills"], ref["fills"])]
    assert max(diffs) < 0.01

    # WHEN in the session each fill landed, not just on which day. Most of
    # this algorithm's fills are pinned to a time by the RULE that fires
    # them -- in the frozen reference, 283 entries and average-downs at
    # 09:31, 67 of the 68 end-of-week exits at 14:00, the four backstop
    # exits at 15:59 -- so a schedule rebuilt off a different anchor, a
    # consolidator emitting on a different boundary, or a fill priced from
    # the next bar moves `ms` while leaving (day, qty) untouched. Live,
    # that is the difference between selling into the 2pm book and selling
    # at the close.
    got_ms = [(f["day"], f["ms"]) for f in res["fills"]]
    want_ms = [(f["day"], f["ms"]) for f in ref["fills"]]
    assert got_ms == want_ms, _first_diff(got_ms, want_ms, "fill times")

    # The whole equity curve, not just its last point. Marking is what the
    # sleeve reports every day it is live and what every drawdown and
    # Sharpe figure is computed from; a mid-curve change that nets out by
    # the end -- a different mark price, a fee applied on the wrong day, an
    # unrealised P&L that ignores a same-day round trip -- changes no fill
    # at all. Cent-exact, on the round(v, 2) the golden harness uses
    # (parity._digest), because the fixture stores raw floats.
    assert res["equity_days"] == ref["equity_days"], \
        _first_diff(res["equity_days"], ref["equity_days"], "equity days")
    assert len(res["equity"]) == len(ref["equity"]) == ref["stats"]["days"]
    got_eq = [round(v, 2) for v in res["equity"]]
    want_eq = [round(v, 2) for v in ref["equity"]]
    assert got_eq == want_eq, _first_diff(got_eq, want_eq, "equity curve")


@needs_data
def test_tqqq_weekly_matches_the_published_lean_numbers():
    """The external oracle, stated as numbers rather than as an engine.
    Tolerances are LEAN's own reporting precision, not slack: LEAN computes
    in C# decimal and rounds its summary, so end equity is exact to the
    cent while CAGR/Sharpe/drawdown are quoted to 3-4 figures."""
    res, lean = _run(), json.load(open(REF))["lean"]

    assert round(res["stats"]["end_equity"], 2) == lean["end_equity"]
    assert res["stats"]["fills"] == 520
    assert abs(res["stats"]["cagr_pct"] - lean["cagr_pct"]) < 0.2
    assert abs(res["stats"]["max_drawdown_pct"]
               - lean["max_drawdown_pct"]) < 1.0
    assert abs(res["stats"]["sharpe"] - lean["sharpe"]) < 0.1
