"""Indicator parity against REAL LEAN.

`lean_reference.json` is generated by tools/lean_reference.py inside the
quantconnect/lean image: the same 60-bar series fed to LEAN's own indicators,
with the resulting values recorded. Regenerate with:

    docker run --rm -v $PWD/tools:/t --entrypoint bash quantconnect/lean:latest \
      -c "pip install -q clr_loader pythonnet && cd /Lean/Launcher/bin/Debug \
          && python /t/lean_reference.py"

This is the difference between "we implemented the textbook definition" and
"we match LEAN". It has already earned its keep: it caught MomentumPercent
returning a fraction where LEAN returns a percent (100x), TriangularMovingAverage
splitting an even period wrongly, and OnBalanceVolume not seeding with the
first bar's volume. None of those are visible by reading a definition.

TOLERANCE: LEAN computes in C# `decimal` (base-10, 28 digits); we compute in
float64, so values drift in the 5th significant figure over 60 bars — worst
for the triple-smoothed and accumulating ones (Trix, NATR, ChaikinMoneyFlow
all land at ~1.5e-4).

2e-4 relative is set to DISCRIMINATE, not to pass. The smallest real bug this
file caught was TriangularMovingAverage at 3.8e-3 — a 19x margin — and the
rest were far larger: OnBalanceVolume 3.2%, AbsolutePriceOscillator 28%,
MomentumPercent 100x. Tighter than this fails on arithmetic rather than
logic, and a test that cries wolf gets muted.
"""
import json
import os

import pytest

from dqengine.runtime import indicators as I

REF = json.load(open(os.path.join(os.path.dirname(__file__),
                                  "lean_reference.json")))
BARS = REF["bars"]
TOL = 2e-4

# name -> (factory, bar_fed)
CASES = {
    "SimpleMovingAverage": (lambda: I.SimpleMovingAverage(10), False),
    "ExponentialMovingAverage": (lambda: I.ExponentialMovingAverage(10), False),
    "RelativeStrengthIndex": (lambda: I.RelativeStrengthIndex(14), False),
    "StandardDeviation": (lambda: I.StandardDeviation(10), False),
    "Maximum": (lambda: I.Maximum(10), False),
    "Minimum": (lambda: I.Minimum(10), False),
    "Sum": (lambda: I.Sum(10), False),
    "Momentum": (lambda: I.Momentum(10), False),
    "MomentumPercent": (lambda: I.MomentumPercent(10), False),
    "RateOfChange": (lambda: I.RateOfChange(10), False),
    "RateOfChangePercent": (lambda: I.RateOfChangePercent(10), False),
    "RateOfChangeRatio": (lambda: I.RateOfChangeRatio(10), False),
    "LogReturn": (lambda: I.LogReturn(10), False),
    "Variance": (lambda: I.Variance(10), False),
    "MeanAbsoluteDeviation": (lambda: I.MeanAbsoluteDeviation(10), False),
    "LinearWeightedMovingAverage": (
        lambda: I.LinearWeightedMovingAverage(10), False),
    "TriangularMovingAverage": (lambda: I.TriangularMovingAverage(10), False),
    "DoubleExponentialMovingAverage": (
        lambda: I.DoubleExponentialMovingAverage(10), False),
    "TripleExponentialMovingAverage": (
        lambda: I.TripleExponentialMovingAverage(10), False),
    "HullMovingAverage": (lambda: I.HullMovingAverage(10), False),
    "WilderMovingAverage": (lambda: I.WilderMovingAverage(10), False),
    "ZeroLagExponentialMovingAverage": (
        lambda: I.ZeroLagExponentialMovingAverage(10), False),
    "Trix": (lambda: I.Trix(10), False),
    "AverageTrueRange": (lambda: I.AverageTrueRange(10), True),
    "TrueRange": (lambda: I.TrueRange(), True),
    "NormalizedAverageTrueRange": (
        lambda: I.NormalizedAverageTrueRange(10), True),
    "MidPrice": (lambda: I.MidPrice(10), True),
    "InternalBarStrength": (lambda: I.InternalBarStrength(), True),
    "WilliamsPercentR": (lambda: I.WilliamsPercentR(14), True),
    "CommodityChannelIndex": (lambda: I.CommodityChannelIndex(20), True),
    "OnBalanceVolume": (lambda: I.OnBalanceVolume(), True),
    "ChaikinMoneyFlow": (lambda: I.ChaikinMoneyFlow(20), True),
    "MoneyFlowIndex": (lambda: I.MoneyFlowIndex(14), True),
    "VolumeWeightedMovingAverage": (
        lambda: I.VolumeWeightedMovingAverage(10), True),
    "ParabolicStopAndReverse": (lambda: I.ParabolicStopAndReverse(), True),
    "AverageDirectionalIndex": (lambda: I.AverageDirectionalIndex(14), True),
    "AccumulationDistribution": (lambda: I.AccumulationDistribution(), True),
    "ChandeMomentumOscillator": (lambda: I.ChandeMomentumOscillator(10), False),
    "AbsolutePriceOscillator": (lambda: I.AbsolutePriceOscillator(5, 10), False),
    "PercentagePriceOscillator": (
        lambda: I.PercentagePriceOscillator(5, 10), False),
    # wave 5
    "KaufmanEfficiencyRatio": (lambda: I.KaufmanEfficiencyRatio(10), False),
    "KaufmanAdaptiveMovingAverage": (
        lambda: I.KaufmanAdaptiveMovingAverage(10), False),
    "T3MovingAverage": (lambda: I.T3MovingAverage(10), False),
    "McGinleyDynamic": (lambda: I.McGinleyDynamic(10), False),
    "LeastSquaresMovingAverage": (
        lambda: I.LeastSquaresMovingAverage(10), False),
    "TimeSeriesForecast": (lambda: I.TimeSeriesForecast(10), False),
    "DetrendedPriceOscillator": (
        lambda: I.DetrendedPriceOscillator(10), False),
    "Momersion": (lambda: I.Momersion(10, 20), False),
    "AverageRange": (lambda: I.AverageRange(10), True),
    "SmoothedOnBalanceVolume": (lambda: I.SmoothedOnBalanceVolume(10), True),
    # wave 5 batch 2
    "ChoppinessIndex": (lambda: I.ChoppinessIndex(14), True),
    "MassIndex": (lambda: I.MassIndex(9, 25), True),
    "EaseOfMovementValue": (lambda: I.EaseOfMovementValue(10, 10000), True),
    "ForceIndex": (lambda: I.ForceIndex(10), True),
    "UltimateOscillator": (lambda: I.UltimateOscillator(7, 14, 28), True),
    "DeMarkerIndicator": (lambda: I.DeMarkerIndicator(14), True),
    "AwesomeOscillator": (lambda: I.AwesomeOscillator(5, 34), True),
    "RogersSatchellVolatility": (
        lambda: I.RogersSatchellVolatility(10), True),
    "AccumulationDistributionOscillator": (
        lambda: I.AccumulationDistributionOscillator(5, 10), True),
    "AverageDirectionalMovementIndexRating": (
        lambda: I.AverageDirectionalMovementIndexRating(14), True),
    # wave 5 batch 3
    "HeikinAshi": (lambda: I.HeikinAshi(), True),
    "CoppockCurve": (lambda: I.CoppockCurve(5, 8, 6), False),
    "TrueStrengthIndex": (lambda: I.TrueStrengthIndex(10, 5, 4), False),
    "ConnorsRelativeStrengthIndex": (
        lambda: I.ConnorsRelativeStrengthIndex(3, 2, 10), False),
    "SuperTrend": (lambda: I.SuperTrend(10, 3.0), True),
    "Vortex": (lambda: I.Vortex(10), True),
    "HurstExponent": (lambda: I.HurstExponent(20, 5), False),
    # wave 5 batch 5
    "AccelerationBands": (lambda: I.AccelerationBands(20, 4.0), True),
    "RegressionChannel": (lambda: I.RegressionChannel(10, 2.0), False),
    "WilderSwingIndex": (lambda: I.WilderSwingIndex(3.0), True),
    "WilderAccumulativeSwingIndex": (
        lambda: I.WilderAccumulativeSwingIndex(3.0), True),
    "VariableIndexDynamicAverage": (
        lambda: I.VariableIndexDynamicAverage(10), False),
    "PremierStochasticOscillator": (
        lambda: I.PremierStochasticOscillator(10, 5), True),
    "KnowSureThing": (
        lambda: I.KnowSureThing(5, 5, 8, 5, 11, 5, 14, 8, 9), False),
    "DerivativeOscillator": (
        lambda: I.DerivativeOscillator(14, 5, 3, 9), False),
    "ValueAtRisk": (lambda: I.ValueAtRisk(20, 0.99), False),
    "ChaikinOscillator": (lambda: I.ChaikinOscillator(3, 10), True),
    "RelativeMovingAverage": (lambda: I.RelativeMovingAverage(10), False),
    "RelativeVigorIndex": (lambda: I.RelativeVigorIndex(10, "Wilders"), True),
    # solved from LEAN's source after black-box probing failed
    "ArnaudLegouxMovingAverage": (
        lambda: I.ArnaudLegouxMovingAverage(10), False),
    "FisherTransform": (lambda: I.FisherTransform(10), True),
    "AugenPriceSpike": (lambda: I.AugenPriceSpike(20), False),
    "FractalAdaptiveMovingAverage": (
        lambda: I.FractalAdaptiveMovingAverage(16), True),
    "KlingerVolumeOscillator": (
        lambda: I.KlingerVolumeOscillator(34, 55, 13), True),
    "WaveTrendOscillator": (lambda: I.WaveTrendOscillator(10, 21, 4), True),
    "SchaffTrendCycle": (lambda: I.SchaffTrendCycle(10, 12, 26), False),
}

# Sub-series that must match too — the scalar Current.Value is not always
# the interesting number (Vortex reports the mean of its legs; a strategy
# reads the legs).
SUB_CASES = {
    "Vortex": (lambda: I.Vortex(10), True,
               {"plus": lambda x: x.plus_vortex.value,
                "minus": lambda x: x.minus_vortex.value}),
    "StochasticRelativeStrengthIndex": (
        lambda: I.StochasticRelativeStrengthIndex(14, 14, 3, 3), False,
        {"k": lambda x: x.k.value, "d": lambda x: x.d.value}),
    "BollingerBands": (lambda: I.BollingerBands(10, 2), False,
                       {"upper": lambda x: x.upper_band.value,
                        "middle": lambda x: x.middle_band.value,
                        "lower": lambda x: x.lower_band.value}),
    "AverageDirectionalIndex": (lambda: I.AverageDirectionalIndex(14), True,
                                {"pdi": lambda x: x.positive.value,
                                 "ndi": lambda x: x.negative.value}),
    # these report the INPUT PRICE as their scalar, LEAN included — the
    # lines are the whole point of them
    "IchimokuKinkoHyo": (lambda: I.IchimokuKinkoHyo(9, 26, 17, 52, 26, 26),
                         True, {"tenkan": lambda x: x.tenkan.value,
                                "kijun": lambda x: x.kijun.value}),
    "ChandeKrollStop": (lambda: I.ChandeKrollStop(5, 2.0, 10), True,
                        {"short_stop": lambda x: x.short_stop.value,
                         "long_stop": lambda x: x.long_stop.value}),
    "KlingerVolumeOscillator": (
        lambda: I.KlingerVolumeOscillator(34, 55, 13), True,
        {"signal": lambda x: x.signal.value}),
}

# Nothing is known-divergent any more: the two that were (ChandeMomentum-
# Oscillator's Wilder smoothing, Absolute/PercentagePriceOscillator's SIMPLE
# rather than exponential legs) were both resolved by interrogating LEAN
# directly with tools/lean_probe.py instead of guessing. Keep this dict --
# an honest exemption with a test behind it beats a quiet mismatch.
KNOWN_DIFFERENT = {}


def feed(ind, bar_fed):
    for _t, o, h, lo, c, v in BARS:
        if bar_fed:
            ind.update_bar(None, h, lo, c, v, o)
        else:
            ind.update(None, c)
    return ind.value


@pytest.mark.parametrize("name", sorted(CASES))
def test_matches_lean(name):
    expected = REF["values"].get(name, {}).get("value")
    assert expected is not None, f"no LEAN reference captured for {name}"
    make, bar_fed = CASES[name]
    got = feed(make(), bar_fed)
    assert got == pytest.approx(expected, rel=TOL, abs=1e-6), (
        f"{name}: LEAN {expected}, ours {got}")


@pytest.mark.parametrize("name", sorted(SUB_CASES))
def test_sub_series_match_lean(name):
    make, bar_fed, subs = SUB_CASES[name]
    ind = make()
    for _t, o, h, lo, c, v in BARS:
        if bar_fed:
            ind.update_bar(None, h, lo, c, v, o)
        else:
            ind.update(None, c)
    for key, read in subs.items():
        expected = REF["values"].get(name, {}).get(key)
        if expected is None:
            continue
        assert read(ind) == pytest.approx(expected, rel=TOL, abs=1e-6), (
            f"{name}.{key}: LEAN {expected}, ours {read(ind)}")


def test_the_reference_covers_what_we_claim():
    """A guard: if someone adds an indicator to CASES with no LEAN value,
    the parametrised test above would silently pass nothing."""
    missing = [n for n in CASES
               if REF["values"].get(n, {}).get("value") is None]
    assert missing == [], f"no LEAN reference for: {missing}"


def test_known_divergences_are_still_divergent():
    """If one of these starts matching, it was fixed — take it off the list
    and put it under test. A stale exemption is how a fixed bug goes back to
    being untested."""
    assert KNOWN_DIFFERENT == {}, (
        "exemptions exist but the check for them was removed; re-add it")
